### ISSUE TITLE
CSS needs a lot of help

### ISSUE THREAD

**Issue by mhtess** [mhtess/gen-games#16]
- [x] General: Font is kind of big / clunk. Start Experiment button is kind of small.
- [x] Learning page (Welcome to critter country): 
  - [x] label should more clearly correspond to creature (perhaps it should be below?, dotted lines between creatures?)
  - [x] creatures should grey out when not clicked 
  - [x] more interesting displays of internal features (perhaps skull & crossbones; egg; perhaps with legend)

Chat room? Test page?

**Comment by ashulman18** [comment]
waiting on MH's review to close this issue
