### ISSUE TITLE
Record data

### ISSUE THREAD

**Issue by mhtess** [mhtess/gen-games#18]
Messages from Robert:

> I recently overhauled the data interface to this function called `dataOutput` that simply specifies callbacks for each event in onMessage that you want to record -- example here: https://github.com/hawkrobe/reference_games/blob/master/experiments/3dObjects/chatbox_basic/game.server.js#L71-L144

> robert_hawkins [15:09]  that's the only function you need in your local experiment! You'll need to pull in upstream master because all the changes are on the back-end (I totally rewrote the `serverBase` class) (edited)

Since our repo is disconnected from `reference_games`, I would instead look at what changes were made to `serverBase` recently:  https://github.com/hawkrobe/reference_games/commits/master/experiments/sharedUtils/serverBase.js

> the logic is you specify the object to bundle up from each event's message in `dataOutput` and the back-end writes it to the places you want it to be written (either `csv` or `mongo`, which you put in `this.dataStore`) https://github.com/hawkrobe/reference_games/blob/master/experiments/categorical/artificial/game.core.js#L41-L42

**Comment by ashulman18** [comment]
Do we want to keep score? If so, this needs to be monitored in the data (so players can get paid(?) accordingly). If we decide to, this should lead to another issue of actually creating relevant text

**Comment by mhtess** [comment]
We do want to keep score. (and in general, record responses and the displayed stimuli on all trials). I'm not sure we want to display the score to the participants so if that's what you meant by "relevant text", I think you can hold off on it for now.

**Comment by mhtess** [comment]
I have started to address this in the `recordData` branch. In a nut shell, in `mp-game.js`, when `log_responses()` gets called (or inside `button()`), a JSON object is made with all the fields you want to record. Then, you emit 
`globalGame.socket.send("logResponse.testCritters." + _.pairs(dataToSend).join('.'));`
where `_.pairs()` turns the object into an array of arrays. 

On the server end (`game.server`), all one needs to do is export a function from `dataOutput()` whose name matches the name of the emit (e.g., `"logResponse"`). This function will receive the message sent i n the emit, and return an object that you want to record. In this example, all this function does is remake a JSON object from this array of arrays.

**Comment by mhtess** [comment]
We are currently able to write to csv for training, test trials and subject info. We may still need to record more information than we are currently, but the basic functionality is there.
