### ISSUE TITLE
Fix / change the disconnect screen

### ISSUE THREAD

**Issue by ashulman18** [mhtess/gen-games#20]
Right now, it's still what Robert had and sometimes the continue button from whatever page it left is still on there (and clickable!). This needs some help

**Comment by mhtess** [comment]
Potentially relevant notes from Robert re: posting to turk / connection / disconnection
robert_hawkins [02:22] 
ah, you run it the same way you run any other expt -- cosub (or submitorator)


[02:23] 
you just have to have `node app.js ...` running on the server for the forms to show up in turk


[02:24] 
I forget how you set up it -- did you keep my `consent.html` -> `instructions.html` -> `pass.html` then a button that takes you to a new tab with the experiment running?


[02:26] 
regardless, you set the url in your cosub settings.json to be the consent form (e.g. `https://rxdhawkins.me:<port>/path/to/form.html`)


[02:27] 
then at some there's a page w/ mmturkey imported that opens up your `index.html` w/ socket.io and so on in a new tab


[02:28] 
that's just cause socket.io won't work inside the turk iframe


[02:28] 
e.g. https://github.com/hawkrobe/reference_games/blob/master/experiments/categorical/artificial/forms/pass.html
