### ISSUE TITLE
Correct data encoding on message data recording

### ISSUE THREAD

**Issue by la-oey** [mhtess/gen-games#23]
- [x] The message data recording records the round number as always being 1. Issue might be in the client file, instead of server
- [ ] Inclusion of critters for the given round will be extremely useful
- [x] Include time for a given round, or at least time in chatroom

- [ ] Concaternate all individual game data recordings for a given experiment into a single file (not sure if to do this via R or directly from the server (e.g. adding data to the same file)

**Comment by mhtess** [comment]
What is missing to resolve this issue?

**Comment by mhtess** [comment]
This is a sub-issue of #18 , so I'm closing it for now
