### ISSUE TITLE
Fix comprehension question about "proceed at own pace"

### ISSUE THREAD

**Issue by mhtess** [mhtess/gen-games#38]
I suspect many people aren't understanding this question, which would prevent them from accepting the HIT, which decreases the flow of traffic, which upsets turkers.

**Comment by la-oey** [comment]
Include in instructions that critter order will be randomized in test for both players, some turkers are listing the order of the critters

**Comment by mhtess** [comment]
Robert uses a question like this: https://github.com/hawkrobe/reference_games/blob/master/experiments/categorical/artificial/forms/instructions.html#L197

We should adopt a similar question to replace the "proceed at own pace" question. See how he describes it in the instructions for him
