### ISSUE TITLE
Fix data recording after first pilot

### ISSUE THREAD

**Issue by la-oey** [mhtess/gen-games#40]
The trialNum value in all of the data recording file currently starts at 2 and ends at 5, this should be fixed to 1->4

Only seems to affect logScores, logTest, logTrain

**Comment by mhtess** [comment]
1. Distribution information in learn critters and test critters - 
Record the probability of the species having an internal feature with each individual critter

**Comment by la-oey** [comment]
Remove full_internal_prop vector recording in logTest

**Comment by la-oey** [comment]
trialNum and block_num are redundant in logTest and logTrain

**Comment by mhtess** [comment]
@ashulman18 Have you checked that the data is being written to file?

**Comment by ashulman18** [comment]
We simply need to check that this data is being written to file. I have trouble checking our data files to make sure this is done. With MH's recent commit, I think we should be done with this. Just need to check and make sure
