### ISSUE TITLE
Classical category learning version of the task

### ISSUE THREAD

**Issue by mhtess** [mhtess/gen-games#45]
Basic idea is that training will involve learning the label (e.g., fep vs. wug), where the (boolean) properties vary across exemplars. We should pick out a simple example from the boolean category learning paradigm. 

The game core should be refactored a bit to allow for easy manipulation of the concepts.

**Comment by ashulman18** [comment]
This is mp-game-2's current state. This version is almost done except for the problem in the comment on #44
